services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-pass-gen
    command: gunicorn --bind 0.0.0.0:8000 manage:app
    restart: on-failure
    ports:
      - 8000:8000
    env_file:
      - ./.env
